### ISSUE TITLE
Links to slack discussions

### ISSUE THREAD

**Issue by PixelPartner** [rofrol/elm-ui-cookbook#1]
You often added `https://elmlang.slack.com` and `#elm-ui` to the topics.

Have you tried to directly link to the specific discussion like [example slack link](https://elmlang.slack.com/archives/C4F9NBLR1/p1573943528484100) ?

You can get the link in the Slack-App UI under the `...` menu of the thread.

**Comment by rofrol** [comment]
I add this because history is not available in slack conversations for too long (probably unless you pay). There was slackarchive.io or similar but is not functioning now.

**Comment by PixelPartner** [comment]
I haven't thought of that. Thank you.
